version: "3.9"
services:
    client:
        container_name: carboy-client
        image: rparks/cb-client
        restart: unless-stopped
        volumes:
            - ./SERVER_URL.js:/app/dist/SERVER_URL.js
    server:
        container_name: carboy-server
        image: rparks/cb-server
        restart: unless-stopped
        environment:
            MONGO_URL: mongo:27017
            MONGO_USER: root
            MONGO_PASS: example
            DEFAULT_ADMIN_USERNAME: admin
            DEFAULT_ADMIN_PASSWORD: pass
            DEFAULT_ADMIN_FULLNAME: Default Admin
            CREATE_DEFAULT_ADMIN: true
            JWT_PRIVATE_KEY: securePrivateKey
        volumes:
            - ./images:/app/images
        depends_on:
            - mongo
    mongo:
        container_name: carboy-mongo
        image: mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 127.0.0.1:27017:27017
        volumes:
            - ./data:/data/db
    mongo-express:
        container_name: carboy-mongo-gui
        image: mongo-express
        restart: unless-stopped
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
            ME_CONFIG_BASICAUTH_USERNAME: example
            ME_CONFIG_BASICAUTH_PASSWORD: pass
            ME_CONFIG_SITE_BASEURL: /db/
        depends_on:
            - mongo
    nginx:
        container_name: carboy-web
        image: nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - client
            - server
            - mongo-express
